# Generated by Django 4.2.7 on 2024-02-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_favoritesproducts_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritesProducts',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Артикул товара'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_name',
            field=models.CharField(default=0, max_length=150, unique=True, verbose_name='Название товара'),
            preserve_default=False,
        ),
    ]
