# Generated by Django 4.2.7 on 2024-03-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_favoritesproducts_user_favorites_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites_name',
        ),
    ]
